import { type AppType } from "next/dist/shared/lib/utils";
import { ThemeProvider } from "next-themes";
import "~/styles/globals.css";
import Navbar from "~/components/Navbar";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Countries!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fcdn.onlinewebfonts.com%2Fsvg%2Fimg_431077.png&f=1&nofb=1&ipt=6ceb11c647752f70e4af3cf96af452b1d5fd5687459e2dd693aee7540eb82326&ipo=images"
        />
      </Head>
      <ThemeProvider attribute="class">
        <div className="dark:dark-bg light-bg ">
          <Navbar />
          <Component {...pageProps} />
        </div>
      </ThemeProvider>
    </>
  );
};

export default MyApp;
