import { GetStaticProps, InferGetStaticPropsType, type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Card from "~/components/Card";
import Navbar from "~/components/Navbar";
import Filter from "~/components/Filter";

export const getStaticProps: GetStaticProps<{
  data: [
    {
      name: { common: string; official: string };
      flags: { png: string; alt: string };
      region: string;
      capital: string;
      population: string;
    }
  ];
}> = async function () {
  // really awesome api lol allows u to filter and stuff,
  // appreciate the typesafety provided on getstaticprops
  const res = await fetch("https://restcountries.com/v3.1/all");
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data },
  };
};

//sorts alphabetically then maps over it

const Home = ({ data }: InferGetStaticPropsType<typeof getStaticProps>) => {
  const countries = data
    .sort((a, b) => a.name.common.localeCompare(b.name.common))
    .map((country) => (
      <Card
        key={country.name.official}
        to={country.name.common}
        name={country.name.common}
        flag={{
          src: country.flags.png,
          alt: country.flags.alt,
        }}
        region={country.region}
        capital={country.capital}
        population={country.population}
      />
    ));

  return (
    <>
      <Head>
        <title>Countries!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fcdn.onlinewebfonts.com%2Fsvg%2Fimg_431077.png&f=1&nofb=1&ipt=6ceb11c647752f70e4af3cf96af452b1d5fd5687459e2dd693aee7540eb82326&ipo=images"
        />
      </Head>

      <div className="flex flex-wrap justify-center gap-8  p-6  md:p-10 xl:gap-10">
        <Filter />
        {countries}
      </div>
    </>
  );
};

export default Home;
